docs: Update FAQ.md
paritytech/parity-signer pull request #1004
Opened 2022-04-20 21:04 UTC by goldsteinsveta

2022-04-20 21:13 UTC, Slesarew commented
Consider also adding info from this stale branch (or reviving it). https://github.com/paritytech/parity-signer/pull/776

2022-04-23 19:05 UTC, Slesarew requested changes

2022-04-25 11:08 UTC, goldsteinsveta commented on docs/src/wiki/FAQ.md
> +	If you are importing a derived key, in the screen of the imported seed select the account's network, press "Plus" icon next to "Derived keys", enter your derivation path.
This is only relevant for derived keys? The "select network" step is there

2022-04-25 12:09 UTC, Slesarew commented on docs/src/wiki/FAQ.md
> +	If you are importing a derived key, in the screen of the imported seed select the account's network, press "Plus" icon next to "Derived keys", enter your derivation path.
yes, you are right.

2022-04-25 12:15 UTC, Slesarew approved these changes

2022-04-25 13:06 UTC, TriplEight approved these changes

2022-04-25 15:02 UTC, merged