Fix scripts for android and related doc
paritytech/parity-signer pull request #708
Opened 2021-01-10 17:43 UTC by Tbaut

closes #707

2021-01-11 18:12 UTC, kirushik commented on package.json
> +    "build:ios": "yarn install && npx pod-install",
Maybe let's call it `install:ios` while we're at it?
It is really confusing to have a `build` target which doesn't, well, _build_ anything.

2021-01-12 13:29 UTC, TriplEight requested changes
Looks good, except it needs an explanation what `yarn install:ios` does.

2021-01-12 13:29 UTC, TriplEight commented on docs/wiki/Building-And-Publishing.md
> +1. Switch to the `master` branch and run `yarn install:ios`
```suggestion
1. Switch to the `master` branch and build the dependencies with `yarn install:ios`
```

2021-01-12 14:24 UTC, Tbaut commented on docs/wiki/Building-And-Publishing.md
> +1. Switch to the `master` branch and build the dependencies with `yarn install:ios`
```suggestion
1. Switch to the `master` branch and install the dependencies with `yarn install:ios`
```

2021-01-12 19:21 UTC, TriplEight submitted a review, later dismissed

2021-01-12 20:14 UTC, Tbaut commented
Not sure why this E2E test is hanging for hours and timing out... It failed in the last merge to master. I don't think it's related to this PR, but we should take a look.

2021-01-13 17:21 UTC, merged