fix: update metadata
paritytech/parity-signer pull request #735
Opened 2021-03-10 11:39 UTC by Slesarew

Update almost all metadata to today morning's state.
Please check carefully.

2021-03-10 12:55 UTC, dvdplm requested changes

2021-03-10 12:55 UTC, dvdplm commented on src/constants/networkMetadata.ts
> +// TODO: automate updates
I think it's better to add an issue than a TODO. If you want the todo in the code it should be "TODO: automate updates (issue: … …)"

2021-03-11 14:54 UTC, TarikGul approved these changes
Just as a note for the PR, there are 4 networks that the Metdata changed for:

Westend,
Edgeware
Polkadot
Rococo

LGTM, but I agree with David and would like to see that change as well for the comment.

2021-03-11 16:37 UTC, s3krit approved these changes
LGTM - are you just getting this by calling `state_getMetadata` with `websocat` or similar?

2021-03-11 17:50 UTC, Slesarew commented
> LGTM, but I agree with David and would like to see that change as well for the comment.
But it's done, just waiting for David to confirm whether he likes it or not.

2021-03-11 17:52 UTC, Slesarew commented
> LGTM - are you just getting this by calling `state_getMetadata` with `websocat` or similar?

yes, these I pulled by manually querying the polkadot.js

2021-03-11 19:26 UTC, TarikGul commented
> But it's done, just waiting for David to confirm whether he likes it or not. 

@Slesarew Oh nice, my bad. For some reason I overlooked it.

2021-03-12 09:09 UTC, dvdplm approved these changes

2021-03-12 09:18 UTC, merged